[workspace]
members = ["simulation"]
default-members = ["simulation"]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.13.2" }
iyes_perf_ui = "0.2.3"
rusty-hook = "0.11.2"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
