[package]
name = "simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_editor_pls = { workspace = true }
bevy_rapier2d = { workspace = true }
iyes_perf_ui = { workspace = true }
